services:
  service-book:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-book:v1
    env_file:
      - .env
    environment:
      - PORT=8010
    ports:
      - "8001:8010"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
    depends_on:
      - db

  db:
    image: mysql:8.0
    expose:
      - 33067
    ports:
      - "33067:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
        MYSQL_ROOT_PASSWORD: root
    restart: always

volumes:
  db_data: