services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8001"]

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_DATABASE: book
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - "33067:3306"