apiVersion: v1
kind: Service
metadata:
  name: {{ include "book.fullname" . }}-grpc
spec:
  type: {{ .Values.grpc.service.type }}
  ports:
    - port: {{ .Values.grpc.service.port }}
      targetPort: {{ .Values.grpc.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "book.fullname" . }}-grpc
