apiVersion: v1
kind: Service
metadata:
  name: {{ include "book.fullname" . }}
spec:
  type: {{ .Values.book.service.type }}
  ports:
    - port: {{ .Values.book.service.port }}
      targetPort: {{ .Values.book.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "book.fullname" . }}
