apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-book-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-book-deployment
  template:
    metadata:
      labels:
        app: service-book-deployment
    spec:
      containers:
        - name: service-book
          image: registry.digitalocean.com/rso-vaje/service-book:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: django-k8s-book-prod-env
          env:
            - name: PORT
              value: "8001"
          ports:
            - containerPort: 8001
      imagePullSecrets:
        - name: registry-rso-vaje

---

apiVersion: v1
kind: Service
metadata:
  name: service-book-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: service-book-deployment
